from __future__ import annotations

import hashlib
import re
from datetime import timedelta

from fastapi import APIRouter, Depends, Request, Response
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session

from app.config import get_settings
from app.database import get_db
from app.models import User
from app.placement_access import utcnow_naive
from app.telemetry_models import PageViewEvent
from app.utils import decode_token

router = APIRouter(prefix="/telemetry", tags=["Telemetry"])
settings = get_settings()

_ID_RE = re.compile(r"^[A-Za-z0-9_-]{16,128}$")
_HOST_RE = re.compile(r"^[A-Za-z0-9.-]{1,200}$")


class PageViewIn(BaseModel):
    visitor_id: str = Field(min_length=16, max_length=128)
    session_id: str = Field(min_length=16, max_length=128)
    path: str = Field(min_length=1, max_length=240)
    referrer_host: str | None = Field(default=None, max_length=200)


def _hash_client_id(value: str) -> str:
    return hashlib.sha256(f"{settings.jwt_secret_key}|{value}".encode("utf-8")).hexdigest()


def _optional_user(request: Request, db: Session) -> User | None:
    authorization = request.headers.get("Authorization", "")
    if not authorization.lower().startswith("bearer "):
        return None
    token = authorization.split(" ", 1)[1].strip()
    if not token:
        return None
    try:
        payload = decode_token(token, settings.jwt_secret_key, "access")
        email = str(payload.get("sub") or "").lower()
    except ValueError:
        return None
    if not email:
        return None
    user = db.query(User).filter(User.email == email).first()
    if not user or not user.is_active:
        return None
    if int(payload.get("ver", 0)) != int(user.auth_version or 1):
        return None
    return user


def _clean_path(path: str) -> str:
    cleaned = str(path or "/").strip().split("?", 1)[0].split("#", 1)[0]
    if not cleaned.startswith("/"):
        cleaned = f"/{cleaned}"
    return cleaned[:240] or "/"


@router.post("/page-view", status_code=204)
def page_view(
    body: PageViewIn,
    request: Request,
    db: Session = Depends(get_db),
):
    """Record privacy-safe first-party page-view telemetry.

    The browser sends random IDs generated by PlaceAI itself. The server stores only
    keyed hashes of those IDs, never IP addresses, full referrer URLs, fingerprints,
    passwords, tokens, or page query strings.
    """
    if not _ID_RE.fullmatch(body.visitor_id) or not _ID_RE.fullmatch(body.session_id):
        return Response(status_code=204)

    path = _clean_path(body.path)
    referrer_host = (body.referrer_host or "").strip().lower().rstrip(".")
    if not referrer_host or not _HOST_RE.fullmatch(referrer_host):
        referrer_host = None

    visitor_hash = _hash_client_id(body.visitor_id)
    session_hash = _hash_client_id(body.session_id)
    current_user = _optional_user(request, db)
    now = utcnow_naive()

    duplicate = (
        db.query(PageViewEvent.id)
        .filter(
            PageViewEvent.visitor_hash == visitor_hash,
            PageViewEvent.session_hash == session_hash,
            PageViewEvent.path == path,
            PageViewEvent.created_at >= now - timedelta(seconds=20),
        )
        .first()
    )
    if duplicate:
        return Response(status_code=204)

    db.add(
        PageViewEvent(
            visitor_hash=visitor_hash,
            session_hash=session_hash,
            user_id=current_user.id if current_user else None,
            path=path,
            referrer_host=referrer_host,
            created_at=now,
        )
    )
    db.commit()
    return Response(status_code=204)
